### ISSUE TITLE
AWS Lambda only allows "tmp" folder write access

### ISSUE THREAD

**Issue by seruminar** [serilog-contrib/Serilog.Sinks.AmazonS3#45]
In the implementation of this sink is a little bit of `System.IO.File` and `System.IO.Directory` usage, which makes it difficult to use in environments with a read-only file system. A typical `SelfLog` exception looks like this:

```
2022-04-12T21:08:14.5671772Z Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink: System.IO.IOException: Read-only file system
--
at System.IO.FileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at Serilog.Sinks.AmazonS3.AmazonS3Sink.OpenFile()
at Serilog.Sinks.AmazonS3.AmazonS3Sink.EmitBatchAsync(IEnumerable`1 batch)
at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

The exception is similar if it follows the path where it doesn't first try to create a new directory.

AWS Lambda is one such environment. Luckily, it exposes the `tmp` folder for writing, so prepending `/tmp/` to the `path` parameter of the `AmazonS3` extension method allowed this sink to work.

It may be useful to document this use case somewhere!

**Comment by SeppPenner** [comment]
@all-contributors please add @seruminar for doc

**Comment by SeppPenner** [comment]
Thank you for the contribution. I have added a special notice to the readme :)
